apiVersion: apps/v1
kind: Deployment
metadata:
  name: bb-demo-by-argo
  namespace: demoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web-argo
  template:
    metadata:
      labels:
        bb: web-argo
    spec:
      containers:
        - name: bb-site
          image: getting-started
          imagePullPolicy: Never
