apiVersion: v1
kind: Service
metadata:
  name: bb-entrypoint-argo
  namespace: demoapp
spec:
  type: NodePort
  selector:
    bb: web-argo
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30002